[
  {
    event: 'game-started',
    player: 'lucas',
    playerIndex: '1',
    game: { mode: 'X01', pointsStart: '301', special: 'TODO' },
  },
  {
    event: 'dart1-thrown',
    player: 'lucas',
    playerIndex: '1',
    playerIsBot: 'False',
    game: {
      mode: 'X01',
      pointsLeft: '229',
      dartNumber: '1',
      dartValue: '25',
      fieldName: '25',
      fieldNumber: 25,
      fieldMultiplier: 1,
      coords: { x: -0.05423004601375257, y: -0.030324441366318837 },
      type: 'single',
    },
  },
  {
    event: 'dart2-thrown',
    player: 'lucas',
    playerIndex: '1',
    playerIsBot: 'False',
    game: {
      mode: 'X01',
      pointsLeft: '228',
      dartNumber: '2',
      dartValue: '1',
      fieldName: 's1',
      fieldNumber: 1,
      fieldMultiplier: 1,
      coords: { x: 0.2384237976859892, y: 0.6216391512496073 },
      type: 'singleouter',
    },
  },
  {
    event: 'dart3-thrown',
    player: 'lucas',
    playerIndex: '1',
    playerIsBot: 'False',
    game: {
      mode: 'X01',
      pointsLeft: '216',
      dartNumber: '3',
      dartValue: '12',
      fieldName: 's12',
      fieldNumber: 12,
      fieldMultiplier: 1,
      coords: { x: -0.20007548417540144, y: 0.3122049038651811 },
      type: 'singleinner',
    },
  },
  {
    event: 'darts-thrown',
    player: 'lucas',
    playerIndex: '1',
    playerIsBot: 'False',
    game: { mode: 'X01', pointsLeft: '216', dartNumber: '3', dartValue: '38' },
  },
  {
    event: 'mirror',
    files: [
      {
        caller: 'en-us-gregory-male',
        path: 'C%3A%5CUsers%5Csvene%5CMusic%5Cdarts-caller%5Cen-US-Gregory-Male-v6%5C38.mp3',
        wait: false,
        volume: 1,
        mod: true,
      },
    ],
  },
  { event: 'Board Status', data: { status: 'Takeout Started' } },
  { event: 'Board Status', data: { status: 'Takeout Finished' } },
  {
    event: 'darts-pulled',
    player: 'schwembini',
    playerIndex: '0',
    game: {
      mode: 'X01',
      pointsLeft: '121',
      dartsThrown: '3',
      dartsThrownValue: '38',
      busted: 'False',
    },
  },
  { event: 'Board Status', data: { status: 'Manual reset' } },
  {
    event: 'mirror',
    files: [
      {
        caller: 'en-us-gregory-male',
        path: 'C%3A%5CUsers%5Csvene%5CMusic%5Cdarts-caller%5Cen-US-Gregory-Male-v6%5Cyou_require%2B28.mp3',
        wait: true,
        volume: 1,
        mod: true,
      },
      {
        caller: 'en-us-gregory-male',
        path: 'C%3A%5CUsers%5Csvene%5CMusic%5Cdarts-caller%5Cen-US-Gregory-Male-v6%5C121.mp3',
        wait: true,
        volume: 1,
        mod: true,
      },
    ],
  },
  {
    event: 'dart1-thrown',
    player: 'schwembini',
    playerIndex: '0',
    playerIsBot: 'False',
    game: {
      mode: 'X01',
      pointsLeft: '108',
      dartNumber: '1',
      dartValue: '13',
      fieldName: 's13',
      fieldNumber: 13,
      fieldMultiplier: 1,
      coords: { x: 0.39389539493451603, y: 0.16024715758621735 },
      type: 'singleinner',
    },
  },
  {
    event: 'dart2-thrown',
    player: 'schwembini',
    playerIndex: '0',
    playerIsBot: 'False',
    game: {
      mode: 'X01',
      pointsLeft: '84',
      dartNumber: '2',
      dartValue: '24',
      fieldName: 'd12',
      fieldNumber: 12,
      fieldMultiplier: 2,
      coords: { x: -0.4765298186419556, y: 0.8487228718869915 },
      type: 'double',
    },
  },
  {
    event: 'dart3-thrown',
    player: 'schwembini',
    playerIndex: '0',
    playerIsBot: 'False',
    game: {
      mode: 'X01',
      pointsLeft: '64',
      dartNumber: '3',
      dartValue: '20',
      fieldName: 's20',
      fieldNumber: 20,
      fieldMultiplier: 1,
      coords: { x: -0.0028964085862776146, y: 0.6678352242208814 },
      type: 'singleouter',
    },
  },
  {
    event: 'darts-thrown',
    player: 'schwembini',
    playerIndex: '0',
    playerIsBot: 'False',
    game: { mode: 'X01', pointsLeft: '64', dartNumber: '3', dartValue: '57' },
  },
  {
    event: 'mirror',
    files: [
      {
        caller: 'en-us-gregory-male',
        path: 'C%3A%5CUsers%5Csvene%5CMusic%5Cdarts-caller%5Cen-US-Gregory-Male-v6%5C57.mp3',
        wait: false,
        volume: 1,
        mod: true,
      },
    ],
  },
  { event: 'Board Status', data: { status: 'Takeout Started' } },
  { event: 'Board Status', data: { status: 'Takeout Finished' } },
  {
    event: 'darts-pulled',
    player: 'lucas',
    playerIndex: '1',
    game: {
      mode: 'X01',
      pointsLeft: '216',
      dartsThrown: '3',
      dartsThrownValue: '57',
      busted: 'False',
    },
  },
  { event: 'Board Status', data: { status: 'Manual reset' } },
  {
    event: 'dart1-thrown',
    player: 'lucas',
    playerIndex: '1',
    playerIsBot: 'False',
    game: {
      mode: 'X01',
      pointsLeft: '203',
      dartNumber: '1',
      dartValue: '13',
      fieldName: 's13',
      fieldNumber: 13,
      fieldMultiplier: 1,
      coords: { x: 0.25364624688939624, y: 0.1104118376571605 },
      type: 'singleinner',
    },
  },
  {
    event: 'dart2-thrown',
    player: 'lucas',
    playerIndex: '1',
    playerIsBot: 'False',
    game: {
      mode: 'X01',
      pointsLeft: '202',
      dartNumber: '2',
      dartValue: '1',
      fieldName: 's1',
      fieldNumber: 1,
      fieldMultiplier: 1,
      coords: { x: 0.21762745891939686, y: 0.8638743114836084 },
      type: 'singleouter',
    },
  },
  {
    event: 'dart3-thrown',
    player: 'lucas',
    playerIndex: '1',
    playerIsBot: 'False',
    game: {
      mode: 'X01',
      pointsLeft: '184',
      dartNumber: '3',
      dartValue: '18',
      fieldName: 's18',
      fieldNumber: 18,
      fieldMultiplier: 1,
      coords: { x: 0.31353188227370754, y: 0.5734584861903941 },
      type: 'singleouter',
    },
  },
  {
    event: 'darts-thrown',
    player: 'lucas',
    playerIndex: '1',
    playerIsBot: 'False',
    game: { mode: 'X01', pointsLeft: '184', dartNumber: '3', dartValue: '32' },
  },
  {
    event: 'mirror',
    files: [
      {
        caller: 'en-us-gregory-male',
        path: 'C%3A%5CUsers%5Csvene%5CMusic%5Cdarts-caller%5Cen-US-Gregory-Male-v6%5C32.mp3',
        wait: false,
        volume: 1,
        mod: true,
      },
    ],
  },
  { event: 'Board Status', data: { status: 'Takeout Started' } },
  { event: 'Board Status', data: { status: 'Takeout Finished' } },
  {
    event: 'darts-pulled',
    player: 'schwembini',
    playerIndex: '0',
    game: {
      mode: 'X01',
      pointsLeft: '64',
      dartsThrown: '3',
      dartsThrownValue: '32',
      busted: 'False',
    },
  },
  { event: 'Board Status', data: { status: 'Manual reset' } },
  {
    event: 'mirror',
    files: [
      {
        caller: 'en-us-gregory-male',
        path: 'C%3A%5CUsers%5Csvene%5CMusic%5Cdarts-caller%5Cen-US-Gregory-Male-v6%5Cyou_require%2B27.mp3',
        wait: true,
        volume: 1,
        mod: true,
      },
      {
        caller: 'en-us-gregory-male',
        path: 'C%3A%5CUsers%5Csvene%5CMusic%5Cdarts-caller%5Cen-US-Gregory-Male-v6%5C64.mp3',
        wait: true,
        volume: 1,
        mod: true,
      },
    ],
  },
  {
    event: 'dart1-thrown',
    player: 'schwembini',
    playerIndex: '0',
    playerIsBot: 'False',
    game: {
      mode: 'X01',
      pointsLeft: '39',
      dartNumber: '1',
      dartValue: '25',
      fieldName: '25',
      fieldNumber: 25,
      fieldMultiplier: 1,
      coords: { x: 0.05612112413061519, y: 0.03541239005984995 },
      type: 'single',
    },
  },
  {
    event: 'dart2-thrown',
    player: 'schwembini',
    playerIndex: '0',
    playerIsBot: 'False',
    game: {
      mode: 'X01',
      pointsLeft: '38',
      dartNumber: '2',
      dartValue: '1',
      fieldName: 's1',
      fieldNumber: 1,
      fieldMultiplier: 1,
      coords: { x: 0.2814226247487549, y: 0.6440520980466805 },
      type: 'singleouter',
    },
  },
  {
    event: 'dart3-thrown',
    player: 'schwembini',
    playerIndex: '0',
    playerIsBot: 'False',
    game: {
      mode: 'X01',
      pointsLeft: '38',
      dartNumber: '3',
      dartValue: '0',
      fieldName: 'm3',
      fieldNumber: 3,
      fieldMultiplier: 0,
      coords: { x: 0.18474337497266652, y: -1.1774504702388298 },
      type: 'outside',
    },
  },
  {
    event: 'darts-thrown',
    player: 'schwembini',
    playerIndex: '0',
    playerIsBot: 'False',
    game: { mode: 'X01', pointsLeft: '38', dartNumber: '3', dartValue: '26' },
  },
  {
    event: 'mirror',
    files: [
      {
        caller: 'en-us-gregory-male',
        path: 'C%3A%5CUsers%5Csvene%5CMusic%5Cdarts-caller%5Cen-US-Gregory-Male-v6%5C26.mp3',
        wait: false,
        volume: 1,
        mod: true,
      },
    ],
  },
  { event: 'Board Status', data: { status: 'Takeout Started' } },
  { event: 'Board Status', data: { status: 'Takeout Finished' } },
  {
    event: 'darts-pulled',
    player: 'lucas',
    playerIndex: '1',
    game: {
      mode: 'X01',
      pointsLeft: '184',
      dartsThrown: '3',
      dartsThrownValue: '26',
      busted: 'False',
    },
  },
  { event: 'Board Status', data: { status: 'Manual reset' } },
  {
    event: 'dart1-thrown',
    player: 'lucas',
    playerIndex: '1',
    playerIsBot: 'False',
    game: {
      mode: 'X01',
      pointsLeft: '166',
      dartNumber: '1',
      dartValue: '18',
      fieldName: 's18',
      fieldNumber: 18,
      fieldMultiplier: 1,
      coords: { x: 0.23421507493487992, y: 0.290933730788454 },
      type: 'singleinner',
    },
  },
  {
    event: 'dart2-thrown',
    player: 'lucas',
    playerIndex: '1',
    playerIsBot: 'False',
    game: {
      mode: 'X01',
      pointsLeft: '146',
      dartNumber: '2',
      dartValue: '20',
      fieldName: 's20',
      fieldNumber: 20,
      fieldMultiplier: 1,
      coords: { x: -0.05959190621588183, y: 0.8117732653105044 },
      type: 'singleouter',
    },
  },
  {
    event: 'dart3-thrown',
    player: 'lucas',
    playerIndex: '1',
    playerIsBot: 'False',
    game: {
      mode: 'X01',
      pointsLeft: '126',
      dartNumber: '3',
      dartValue: '20',
      fieldName: 's20',
      fieldNumber: 20,
      fieldMultiplier: 1,
      coords: { x: -0.011665047076167605, y: 0.15210929341571713 },
      type: 'singleinner',
    },
  },
  {
    event: 'darts-thrown',
    player: 'lucas',
    playerIndex: '1',
    playerIsBot: 'False',
    game: { mode: 'X01', pointsLeft: '126', dartNumber: '3', dartValue: '58' },
  },
  {
    event: 'mirror',
    files: [
      {
        caller: 'en-us-gregory-male',
        path: 'C%3A%5CUsers%5Csvene%5CMusic%5Cdarts-caller%5Cen-US-Gregory-Male-v6%5C58.mp3',
        wait: false,
        volume: 1,
        mod: true,
      },
    ],
  },
  { event: 'Board Status', data: { status: 'Takeout Started' } },
  { event: 'Board Status', data: { status: 'Takeout Finished' } },
  {
    event: 'darts-pulled',
    player: 'schwembini',
    playerIndex: '0',
    game: {
      mode: 'X01',
      pointsLeft: '38',
      dartsThrown: '3',
      dartsThrownValue: '58',
      busted: 'False',
    },
  },
  { event: 'Board Status', data: { status: 'Manual reset' } },
  {
    event: 'mirror',
    files: [
      {
        caller: 'en-us-gregory-male',
        path: 'C%3A%5CUsers%5Csvene%5CMusic%5Cdarts-caller%5Cen-US-Gregory-Male-v6%5Cyou_require%2B2.mp3',
        wait: true,
        volume: 1,
        mod: true,
      },
      {
        caller: 'en-us-gregory-male',
        path: 'C%3A%5CUsers%5Csvene%5CMusic%5Cdarts-caller%5Cen-US-Gregory-Male-v6%5C38.mp3',
        wait: true,
        volume: 1,
        mod: true,
      },
    ],
  },
  {
    event: 'dart1-thrown',
    player: 'schwembini',
    playerIndex: '0',
    playerIsBot: 'False',
    game: {
      mode: 'X01',
      pointsLeft: '38',
      dartNumber: '1',
      dartValue: '0',
      fieldName: 'm18',
      fieldNumber: 18,
      fieldMultiplier: 0,
      coords: { x: 0.7212814393403265, y: 0.8151257267182579 },
      type: 'outside',
    },
  },
  {
    event: 'dart2-thrown',
    player: 'schwembini',
    playerIndex: '0',
    playerIsBot: 'False',
    game: {
      mode: 'X01',
      pointsLeft: '34',
      dartNumber: '2',
      dartValue: '4',
      fieldName: 's4',
      fieldNumber: 4,
      fieldMultiplier: 1,
      coords: { x: 0.47277388085351013, y: 0.2769790022224801 },
      type: 'singleinner',
    },
  },
  {
    event: 'dart3-thrown',
    player: 'schwembini',
    playerIndex: '0',
    playerIsBot: 'False',
    game: {
      mode: 'X01',
      pointsLeft: '25',
      dartNumber: '3',
      dartValue: '9',
      fieldName: 's9',
      fieldNumber: 9,
      fieldMultiplier: 1,
      coords: { x: -0.5676236017974043, y: 0.4625913479792909 },
      type: 'singleouter',
    },
  },
  {
    event: 'darts-thrown',
    player: 'schwembini',
    playerIndex: '0',
    playerIsBot: 'False',
    game: { mode: 'X01', pointsLeft: '25', dartNumber: '3', dartValue: '13' },
  },
  {
    event: 'mirror',
    files: [
      {
        caller: 'en-us-gregory-male',
        path: 'C%3A%5CUsers%5Csvene%5CMusic%5Cdarts-caller%5Cen-US-Gregory-Male-v6%5C13.mp3',
        wait: false,
        volume: 1,
        mod: true,
      },
    ],
  },
  { event: 'Board Status', data: { status: 'Takeout Started' } },
  { event: 'Board Status', data: { status: 'Takeout Finished' } },
  {
    event: 'darts-pulled',
    player: 'lucas',
    playerIndex: '1',
    game: {
      mode: 'X01',
      pointsLeft: '126',
      dartsThrown: '3',
      dartsThrownValue: '13',
      busted: 'False',
    },
  },
  { event: 'Board Status', data: { status: 'Manual reset' } },
  {
    event: 'mirror',
    files: [
      {
        caller: 'en-us-gregory-male',
        path: 'C%3A%5CUsers%5Csvene%5CMusic%5Cdarts-caller%5Cen-US-Gregory-Male-v6%5Clucas.mp3',
        wait: false,
        volume: 1,
        mod: true,
      },
      {
        caller: 'en-us-gregory-male',
        path: 'C%3A%5CUsers%5Csvene%5CMusic%5Cdarts-caller%5Cen-US-Gregory-Male-v6%5Cyou_require%2B15.mp3',
        wait: true,
        volume: 1,
        mod: true,
      },
      {
        caller: 'en-us-gregory-male',
        path: 'C%3A%5CUsers%5Csvene%5CMusic%5Cdarts-caller%5Cen-US-Gregory-Male-v6%5C126.mp3',
        wait: true,
        volume: 1,
        mod: true,
      },
    ],
  },
  {
    event: 'dart1-thrown',
    player: 'lucas',
    playerIndex: '1',
    playerIsBot: 'False',
    game: {
      mode: 'X01',
      pointsLeft: '101',
      dartNumber: '1',
      dartValue: '25',
      fieldName: '25',
      fieldNumber: 25,
      fieldMultiplier: 1,
      coords: { x: 0.07337137707668863, y: 0.035379876337092914 },
      type: 'single',
    },
  },
  {
    event: 'dart2-thrown',
    player: 'lucas',
    playerIndex: '1',
    playerIsBot: 'False',
    game: {
      mode: 'X01',
      pointsLeft: '81',
      dartNumber: '2',
      dartValue: '20',
      fieldName: 's20',
      fieldNumber: 20,
      fieldMultiplier: 1,
      coords: { x: 0.0857191722090304, y: 0.6352032133739721 },
      type: 'singleouter',
    },
  },
  {
    event: 'dart3-thrown',
    player: 'lucas',
    playerIndex: '1',
    playerIsBot: 'False',
    game: {
      mode: 'X01',
      pointsLeft: '67',
      dartNumber: '3',
      dartValue: '14',
      fieldName: 's14',
      fieldNumber: 14,
      fieldMultiplier: 1,
      coords: { x: -0.658092320695481, y: 0.16879782862689724 },
      type: 'singleouter',
    },
  },
  {
    event: 'darts-thrown',
    player: 'lucas',
    playerIndex: '1',
    playerIsBot: 'False',
    game: { mode: 'X01', pointsLeft: '67', dartNumber: '3', dartValue: '59' },
  },
  {
    event: 'mirror',
    files: [
      {
        caller: 'en-us-gregory-male',
        path: 'C%3A%5CUsers%5Csvene%5CMusic%5Cdarts-caller%5Cen-US-Gregory-Male-v6%5C59.mp3',
        wait: false,
        volume: 1,
        mod: true,
      },
    ],
  },
  { event: 'Board Status', data: { status: 'Takeout Started' } },
  { event: 'Board Status', data: { status: 'Takeout Finished' } },
  {
    event: 'darts-pulled',
    player: 'schwembini',
    playerIndex: '0',
    game: {
      mode: 'X01',
      pointsLeft: '25',
      dartsThrown: '3',
      dartsThrownValue: '59',
      busted: 'False',
    },
  },
  { event: 'Board Status', data: { status: 'Manual reset' } },
  {
    event: 'mirror',
    files: [
      {
        caller: 'en-us-gregory-male',
        path: 'C%3A%5CUsers%5Csvene%5CMusic%5Cdarts-caller%5Cen-US-Gregory-Male-v6%5Cyou_require%2B8.mp3',
        wait: true,
        volume: 1,
        mod: true,
      },
      {
        caller: 'en-us-gregory-male',
        path: 'C%3A%5CUsers%5Csvene%5CMusic%5Cdarts-caller%5Cen-US-Gregory-Male-v6%5C25.mp3',
        wait: true,
        volume: 1,
        mod: true,
      },
    ],
  },
  {
    event: 'dart1-thrown',
    player: 'schwembini',
    playerIndex: '0',
    playerIsBot: 'False',
    game: {
      mode: 'X01',
      pointsLeft: '20',
      dartNumber: '1',
      dartValue: '5',
      fieldName: 's5',
      fieldNumber: 5,
      fieldMultiplier: 1,
      coords: { x: -0.2837118120120683, y: 0.8301967121384581 },
      type: 'singleouter',
    },
  },
  {
    event: 'busted',
    player: 'schwembini',
    playerIndex: '0',
    playerIsBot: 'False',
    game: {
      mode: 'X01',
      field_name: 't20',
      field_number: 20,
      field_multiplier: 3,
      type: 'triple',
      busted: 'True',
    },
  },
  {
    event: 'mirror',
    files: [
      {
        caller: 'en-us-gregory-male',
        path: 'C%3A%5CUsers%5Csvene%5CMusic%5Cdarts-caller%5Cen-US-Gregory-Male-v6%5Cbusted%2B10.mp3',
        wait: false,
        volume: 1,
        mod: false,
      },
    ],
  },
  { event: 'Board Status', data: { status: 'Takeout Started' } },
  { event: 'Board Status', data: { status: 'Takeout Finished' } },
  {
    event: 'darts-pulled',
    player: 'lucas',
    playerIndex: '1',
    game: {
      mode: 'X01',
      pointsLeft: '67',
      dartsThrown: '3',
      dartsThrownValue: '0',
      busted: 'True',
    },
  },
  { event: 'Board Status', data: { status: 'Manual reset' } },
  {
    event: 'mirror',
    files: [
      {
        caller: 'en-us-gregory-male',
        path: 'C%3A%5CUsers%5Csvene%5CMusic%5Cdarts-caller%5Cen-US-Gregory-Male-v6%5Clucas.mp3',
        wait: false,
        volume: 1,
        mod: true,
      },
      {
        caller: 'en-us-gregory-male',
        path: 'C%3A%5CUsers%5Csvene%5CMusic%5Cdarts-caller%5Cen-US-Gregory-Male-v6%5Cyou_require%2B1.mp3',
        wait: true,
        volume: 1,
        mod: true,
      },
      {
        caller: 'en-us-gregory-male',
        path: 'C%3A%5CUsers%5Csvene%5CMusic%5Cdarts-caller%5Cen-US-Gregory-Male-v6%5C67.mp3',
        wait: true,
        volume: 1,
        mod: true,
      },
    ],
  },
  {
    event: 'dart1-thrown',
    player: 'lucas',
    playerIndex: '1',
    playerIsBot: 'False',
    game: {
      mode: 'X01',
      pointsLeft: '64',
      dartNumber: '1',
      dartValue: '3',
      fieldName: 's3',
      fieldNumber: 3,
      fieldMultiplier: 1,
      coords: { x: 0.05695859481346738, y: -0.542554897214797 },
      type: 'singleinner',
    },
  },
  {
    event: 'dart2-thrown',
    player: 'lucas',
    playerIndex: '1',
    playerIsBot: 'False',
    game: {
      mode: 'X01',
      pointsLeft: '44',
      dartNumber: '2',
      dartValue: '20',
      fieldName: 's20',
      fieldNumber: 20,
      fieldMultiplier: 1,
      coords: { x: -0.0328186624900003, y: 0.7686076915500861 },
      type: 'singleouter',
    },
  },
  {
    event: 'dart3-thrown',
    player: 'lucas',
    playerIndex: '1',
    playerIsBot: 'False',
    game: {
      mode: 'X01',
      pointsLeft: '38',
      dartNumber: '3',
      dartValue: '6',
      fieldName: 's6',
      fieldNumber: 6,
      fieldMultiplier: 1,
      coords: { x: 0.45429534882046985, y: 0.01386646500837237 },
      type: 'singleinner',
    },
  },
  {
    event: 'darts-thrown',
    player: 'lucas',
    playerIndex: '1',
    playerIsBot: 'False',
    game: { mode: 'X01', pointsLeft: '38', dartNumber: '3', dartValue: '29' },
  },
  {
    event: 'mirror',
    files: [
      {
        caller: 'en-us-gregory-male',
        path: 'C%3A%5CUsers%5Csvene%5CMusic%5Cdarts-caller%5Cen-US-Gregory-Male-v6%5C29.mp3',
        wait: false,
        volume: 1,
        mod: true,
      },
    ],
  },
  { event: 'Board Status', data: { status: 'Takeout Started' } },
  { event: 'Board Status', data: { status: 'Takeout Finished' } },
  {
    event: 'darts-pulled',
    player: 'schwembini',
    playerIndex: '0',
    game: {
      mode: 'X01',
      pointsLeft: '25',
      dartsThrown: '3',
      dartsThrownValue: '29',
      busted: 'False',
    },
  },
  { event: 'Board Status', data: { status: 'Manual reset' } },
  {
    event: 'dart1-thrown',
    player: 'schwembini',
    playerIndex: '0',
    playerIsBot: 'False',
    game: {
      mode: 'X01',
      pointsLeft: '5',
      dartNumber: '1',
      dartValue: '20',
      fieldName: 's20',
      fieldNumber: 20,
      fieldMultiplier: 1,
      coords: { x: -0.06542157758706953, y: 0.5301967412335052 },
      type: 'singleinner',
    },
  },
  {
    event: 'busted',
    player: 'schwembini',
    playerIndex: '0',
    playerIsBot: 'False',
    game: {
      mode: 'X01',
      field_name: 's20',
      field_number: 20,
      field_multiplier: 1,
      type: 'singleinner',
      busted: 'True',
    },
  },
  {
    event: 'mirror',
    files: [
      {
        caller: 'en-us-gregory-male',
        path: 'C%3A%5CUsers%5Csvene%5CMusic%5Cdarts-caller%5Cen-US-Gregory-Male-v6%5Cbusted%2B13.mp3',
        wait: false,
        volume: 1,
        mod: false,
      },
    ],
  },
  { event: 'Board Status', data: { status: 'Takeout Started' } },
  { event: 'Board Status', data: { status: 'Takeout Finished' } },
  {
    event: 'darts-pulled',
    player: 'lucas',
    playerIndex: '1',
    game: {
      mode: 'X01',
      pointsLeft: '38',
      dartsThrown: '3',
      dartsThrownValue: '0',
      busted: 'True',
    },
  },
  { event: 'Board Status', data: { status: 'Manual reset' } },
  {
    event: 'mirror',
    files: [
      {
        caller: 'en-us-gregory-male',
        path: 'C%3A%5CUsers%5Csvene%5CMusic%5Cdarts-caller%5Cen-US-Gregory-Male-v6%5Clucas.mp3',
        wait: false,
        volume: 1,
        mod: true,
      },
      {
        caller: 'en-us-gregory-male',
        path: 'C%3A%5CUsers%5Csvene%5CMusic%5Cdarts-caller%5Cen-US-Gregory-Male-v6%5Cyou_require%2B3.mp3',
        wait: true,
        volume: 1,
        mod: true,
      },
      {
        caller: 'en-us-gregory-male',
        path: 'C%3A%5CUsers%5Csvene%5CMusic%5Cdarts-caller%5Cen-US-Gregory-Male-v6%5C38.mp3',
        wait: true,
        volume: 1,
        mod: true,
      },
    ],
  },
  {
    event: 'dart1-thrown',
    player: 'lucas',
    playerIndex: '1',
    playerIsBot: 'False',
    game: {
      mode: 'X01',
      pointsLeft: '31',
      dartNumber: '1',
      dartValue: '7',
      fieldName: 's7',
      fieldNumber: 7,
      fieldMultiplier: 1,
      coords: { x: -0.41303880024915235, y: -0.7129284381516114 },
      type: 'singleouter',
    },
  },
  {
    event: 'dart2-thrown',
    player: 'lucas',
    playerIndex: '1',
    playerIsBot: 'False',
    game: {
      mode: 'X01',
      pointsLeft: '12',
      dartNumber: '2',
      dartValue: '19',
      fieldName: 's19',
      fieldNumber: 19,
      fieldMultiplier: 1,
      coords: { x: -0.0887982104444496, y: -0.36362066977933183 },
      type: 'singleinner',
    },
  },
  {
    event: 'match-won',
    player: 'lucas',
    playerIndex: '1',
    game: {
      mode: 'X01',
      dartsThrown: '3',
      dartsThrownValue: '38',
      fieldName: 's12',
      fieldNumber: 12,
      fieldMultiplier: 1,
      coords: { x: -0.2040724549910608, y: 0.3302948139728753 },
      type: 'singleinner',
    },
  },
  {
    event: 'mirror',
    files: [
      {
        caller: 'en-us-gregory-male',
        path: 'C%3A%5CUsers%5Csvene%5CMusic%5Cdarts-caller%5Cen-US-Gregory-Male-v6%5Cmatchshot%2B6.mp3',
        wait: false,
        volume: 1,
        mod: true,
      },
      {
        caller: 'en-us-gregory-male',
        path: 'C%3A%5CUsers%5Csvene%5CMusic%5Cdarts-caller%5Cen-US-Gregory-Male-v6%5Clucas.mp3',
        wait: true,
        volume: 1,
        mod: true,
      },
    ],
  },
];
